baseURL = "http://www.sebastien-fauvart.fr/"
languageCode = "fr-fr"
title = "Blog"
theme = "minimal"
disqusShortname = "www-sebastien-fauvart-fr" # delete this to disable disqus comments
googleAnalytics = "UA-40228055-5"
staticDir = ["static"]
DefaultContentLanguage = "fr"

[params]
    author = "Sébastien FAUVART"
    description = "Vis ma vie de développeur (couteau ch’ti) passionné"
    githubUsername = "sfauvart"
    accent = "#1B9DEA"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "agate"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "console", "bash", "docker", "dockerfile", "toml"]
    css = ["css/custom.css"]

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

[[menu.main]]
    url = "/mentions-legales"
    name = "Mentions légales"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/sfauvart/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/SebFauvart/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/s%C3%A9bastien-fauvart-a7b2a66b/"
    name = "linkedin"
    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
